### ISSUE TITLE
Make suport to 1.8.9

### ISSUE THREAD

**Issue by HanielCota** [warleysr/autopix#1]
Plss make suporte for this version

**Comment by warleysr** [comment]
Qual erro está acontecendo quando você tenta executar o plugin?

**Comment by HanielCota** [comment]
Amigo os métodos não existem na 1.8 você tem que fazer para a 1.8.

Notei também que o o QR code ao scan fica falando QR code invalido.

Adicione mais Gatways de pagamento tipo pagseguro

**Comment by warleysr** [comment]
A chave PIX estava faltando na payload. Corrigido no a94b753 e gerado a [v1.0.1](https://github.com/warleysr/autopix/releases/tag/v1.0.1).

A versão 1.8 é muito antiga, a compatibilidade é a versão 1.13+.

Sem planos para integrar com PagSeguro.

**Comment by HanielCota** [comment]
Entendo, e uma pena no BR não vamos usar então porque usamos a 1.8 ainda para maior parte das coisas.

**Comment by warleysr** [comment]
Adicionei suporte para MC 1.8 na versão v1.0.2.
