### ISSUE TITLE
Problema na hora de usar o QR

### ISSUE THREAD

**Issue by eaiwesley** [warleysr/autopix#10]
Estou com problema em utilizar o QRCode, quando aponto meu celular para fazer o pagamento o banco diz que a chave pix não existe

**Comment by warleysr** [comment]
Qual tipo de chave está utilizando?Coloque um print da chave pix da sua config tampando alguns caracteres para não expor seus dados.

**Comment by eaiwesley** [comment]
![pix](https://github.com/warleysr/autopix/assets/137367317/717c7662-ff0f-4303-abff-009c0c1e11f1)

**Comment by eaiwesley** [comment]
já tentei com os outros tipos de chave, mas da a mesma coisa

**Comment by warleysr** [comment]
O problema é os caracteres "<>", eles são de exemplo, remova eles. 

O mesmo vale pro token do MP.

**Comment by eaiwesley** [comment]
Funcionou agora kkk, vlw

como é a parte de configuração para ativação sozinha, eu travei nessa parte de site
![image](https://github.com/warleysr/autopix/assets/137367317/d839bbee-b7ad-4f53-8c06-6a0bd6531147)

**Comment by warleysr** [comment]
Você tem que seguir as instruções que tá na página inicial. Tem que configurar os dados no arquivo .php e colocar numa hospedagem e depois configurar a URL nessa parte.

**Comment by eaiwesley** [comment]
quando você cobra pra fazer essa ligação? pois não sei mexer como .php nem webhook

**Comment by warleysr** [comment]
Não cobro, o plugin é totalmente grátis. Coloque sua dúvida para que possa ser esclarecida. Basicamente, é configurar o arquivo PHP com os mesmos dados do banco configurado no plugin.yml e colocá-lo em uma hospedagem (poder ser gratuita ou paga). Se não possui uma hospedagem paga recomendo que utilize a https://www.000webhost.com/cpanel-login. Lembrando que a hospedagem do seu servidor MySQL deve autorizar conexão remota.

**Comment by eaiwesley** [comment]
Assim, criei a conta
![image](https://github.com/warleysr/autopix/assets/137367317/3dbdd613-8d20-4e89-ab8d-a583b525dd6f)
oque eu faço agora?

**Comment by eaiwesley** [comment]
Bom dia @warleysr, aonde coloco o .php?

**Comment by eaiwesley** [comment]
coloquei la, mas mesmo assim ainda não funciona e minha mysql disponibiliza
