### ISSUE TITLE
Onde coloco o .php?

### ISSUE THREAD

**Issue by warleysr** [warleysr/autopix#11]
Bom dia @warleysr, aonde coloco o .php?

_Originally posted by @eaiwesley in https://github.com/warleysr/autopix/issues/10#issuecomment-1647875153_

**Comment by warleysr** [comment]
@eaiwesley Você precisa colocar o .php online no seu site, para isso abra o gerenciador de arquivos e entre na pasta **public_html** e faça o upload do arquivo nesta pasta. Lembrando que o seu MySQL deve aceitar conexão remota para funcionar.

**Comment by warleysr** [comment]
@eaiwesley Coloque um print da parte de configuração do seu arquivo .php aqui, tampando parte dados.

**Comment by eaiwesley** [comment]
![loja](https://github.com/warleysr/autopix/assets/137367317/632a5e3c-6b09-49a9-9ba3-66735d2c8e2c)

**Comment by warleysr** [comment]
Certo, vamos testar se seu banco de dados está configurado corretamente e se aceita conexão remota. Copia e cole o código abaixo e crie um arquivo chamado **debug_notification.php** na mesma pasta onde está o notification.php e configure com os mesmos dados.
```
<?php
    const HOST = "localhost";
    const USER = "dbadmin";
    const PASSWORD = "admindb";
    const DB = "tests";
    
    $conn = new mysqli(HOST, USER, PASSWORD, DB);

    if ($conn->connect_error) {
        http_response_code(500);
        echo $conn->connect_error;
        $conn->close();
        return;
    }

    $conn->close();
 
?>
```

Após salvar, acesse no seu navegador este arquivo assim: http://dominio-do-seu-site/debug_notification.php, se aparecer algum erro seu MySQL não está configurado corretamente, se não aparecer nada está correto e o problema é em outra parte.

**Comment by eaiwesley** [comment]
![image](https://github.com/warleysr/autopix/assets/137367317/9778b817-9cd0-400c-b540-a4ee9eebfde5)
dessa forma?

**Comment by warleysr** [comment]
Sim, acessei aqui e deu erro de conexão: _ProxySQL Error: Access denied for user 'dbadmin'@'....' (using password: YES)_

Lembra de apagar esse arquivo depois que finalizar o debug.

**Comment by eaiwesley** [comment]
não foi salvo os dados do debug, agora alterei mas pra mim da a mesma coisa

**Comment by warleysr** [comment]
Por isso não funcionou. Se os dados configurados estão corretos, sua hospedagem não aceita conexão remota ao MySQL, verifica isso com eles.

**Comment by eaiwesley** [comment]
conversei com eles, e o suporte deles é até 100ms

**Comment by warleysr** [comment]
Como assim 100ms?  Pelo que entendi do erro a conexão nem foi realizada. Você pode tentar encontrar alguma opção de hospedagem que aceita conexão remota, mas gratuita não sei se será tão fácil. Neste caso talvez a melhor opção seja criar uma conta gratuita por 12 meses na Azure: https://www.youtube.com/watch?v=TsYpUWZLPB4

**Comment by eaiwesley** [comment]
Criei o banco de dados e vinculei ao plugin e o webhost, plugin iniciou normalmente mas ainda não sei se está funcionando o webhost https://palladiummc.000webhostapp.com/debug_notification.php

**Comment by warleysr** [comment]
Não está. É o que disse antes: se aparecer algum erro ao acessar essa URL seu banco de dados não está configurado com os dados corretos ou não aceita conexão remota.
