### ISSUE TITLE
Notification.php error

### ISSUE THREAD

**Issue by perseu444** [warleysr/autopix#13]
Tentei colocar o notification.php no plugin, mas ele parece que bugou 
![image](https://github.com/warleysr/autopix/assets/71997803/c1ce74ad-15ab-4862-b199-91f8098c4742)

**Comment by warleysr** [comment]
Este erro estava na criação do QR code e era basicamente o mesmo problema do bug #12 porém para o QR code dinâmico (gerado via API do MP).

Por favor atualize para a versão ![v1.0.11](https://github.com/warleysr/autopix/releases/tag/v1.0.11) que corrige isto.

**Comment by perseu444** [comment]
> Este erro estava na criação do QR code e era basicamente o mesmo problema do bug #12 porém para o QR code dinâmico (gerado via API do MP).
> 
> Por favor atualize para a versão ![v1.0.11](https://github.com/warleysr/autopix/releases/tag/v1.0.11) que corrige isto.

Obrigado, funcionou corretamente.
