### ISSUE TITLE
Como que eu posso compilar o projeto no meu computador?

### ISSUE THREAD

**Issue by mayksilv** [warleysr/autopix#14]
Eu uso o IntelliJ IDEA.

**Comment by warleysr** [comment]
Você tem que clonar o repositório e abrir o projeto na sua IDE. Também precisa adicionar a API do Spigot como dependência.Tem alguns vídeos no YouTube que ensinam: https://youtu.be/2mWbE-ezk-4?si=3k8RR3ktlylOL90f
