### ISSUE TITLE
Menu de produtos

### ISSUE THREAD

**Issue by JVNfsOficial** [warleysr/autopix#15]
Eu utilizei o plugin e vi que tem apenas 1 menu com 1 comando para abrir e ver os produtos, mas minha ideia seria utilizar para vários produtos diferentes porém cada um com seu menu específico. Gostaria de saber se tem alguma forma de adicionar por exemplo na config.yml ali menu: e as configurações do menu, porém seria bem interessante poder criar vários menus personalizados, como exemplo trocar a variável menu: para o nome que vc escolher de uma variável, por exemplo vips_rankup: e poder usar um comando por exemplo /comprarpix (menu) e colocar o nome da variável que está em config.yml...

**Comment by warleysr** [comment]
Adicionei essa funcionada na [v1.0.12](https://github.com/warleysr/autopix/releases/tag/v1.0.12).
