### ISSUE TITLE
Flat File/ SQLite Suporte

### ISSUE THREAD

**Issue by Eisenbahn** [warleysr/autopix#18]
Olá
Gostaria de saber se seria possivel e de interesse, fazer com suporte a Flatflite ou mesmo SQLite, seria mais amigável, por assim dizer.

Gostaria de incentivar financeiramente essa adição também.

Abraço!

**Comment by warleysr** [comment]
Adicionei essa funcionalidade na versão [v1.0.13](https://github.com/warleysr/autopix/releases/tag/v1.0.13).

**Comment by Eisenbahn** [comment]
Testei no 1.7 com a config nova, não parece funcionar ainda :(

Thermos (Hibrido Forge + Bukkit)

[23:05:40] [Server thread/INFO]: [0;36;1m[AutoPix] [0;31;1mErro ao iniciar MySQL. Verifique o erro: Could not create connection to database server. Attempted reconnect 3 times. Giving up.[m


# Servidor MySQL para salvamento dos dados
mysql:
  type: sqlite
  db: tests
  host: localhost
  port: 3306
  user: root
  pass: admin

**Comment by Eisenbahn** [comment]
Acho que vi o prob, vou testar

**Comment by Eisenbahn** [comment]
Deu certo, falha minha da config
