### ISSUE TITLE
Add pre purchase commands [Improvement]

### ISSUE THREAD

**Issue by Eisenbahn** [warleysr/autopix#22]
![image](https://github.com/warleysr/autopix/assets/2753064/c1c686bf-e424-43b0-afc8-7d06b5f4d877)

Como o mapa fica desativado no 1.7, talvez fosse possível add uma config para cada ENTRY de produto no menu onde o usuário possa, por exemplo, executar o comando ao GERAR o pedido no menu.

Dessa forma, o usuário, por exemplo, poderia forçar um teleporte do jogador para o /warp qrvip30dias, onde o warp seria definido para uma imagem. 

O único requerimento para o comando seria usar a variável do player, que já existe no plugin

Abraço!

**Comment by warleysr** [comment]
Adicionada na versão [v1.0.16](https://github.com/warleysr/autopix/releases/tag/v1.0.16).
