### ISSUE TITLE
Erro ao tentar comprar qualquer produto

### ISSUE THREAD

**Issue by GabrielGamer94** [warleysr/autopix#24]
Ao tentar comprar qualquer produto, está dando o seguinte erro
![image](https://github.com/warleysr/autopix/assets/36807090/c4eada05-53f5-4f01-aff6-ab067d872b92)

**Comment by warleysr** [comment]
Posta sua config aqui tirando os dados sensíveis como dados de conexão ao banco e seu token do MP (apagar alguns caracteres já é o suficiente).

**Comment by GabrielGamer94** [comment]
![image](https://github.com/warleysr/autopix/assets/36807090/6becea8a-5703-48a3-8728-29aa7a062ad9)

**Comment by warleysr** [comment]
Digo o arquivo **config.yml** mesmo, pra eu poder ver o que pode ser. Erro 500 na API significa que a requisição não foi feita corretamente, então pode ser algum nome de item com errado ou algo do tipo.

**Comment by GabrielGamer94** [comment]
Coloquei em zip por que não consegui enviar o arquivo .yml

[config.zip](https://github.com/warleysr/autopix/files/14441431/config.zip)

**Comment by warleysr** [comment]
O problema era uma vírgula a mais colocada na payload enviada pra API do MP. Corrigi isso na versão [v1.0.18](https://github.com/warleysr/autopix/releases/tag/v1.0.18), atualize o jar e deve voltar a funcionar.

**Comment by GabrielGamer94** [comment]
Funcionou
![image](https://github.com/warleysr/autopix/assets/36807090/32027479-f738-4fa7-bb90-87c82658aa4d)
