### ISSUE TITLE
"error":"resource not found"

### ISSUE THREAD

**Issue by KaueTech** [warleysr/autopix#25]
when i use the mercadopago api https://api.mercadopago.com/v1/payments/${id} this json is returned 

`{"error":"resource not found","message":"Si quieres conocer los recursos de la API que se encuentran disponibles visita el Sitio de Desarrolladores de MercadoLibre (https://developers.mercadopago.com)"}`

**Comment by warleysr** [comment]
@KaueTech não entendi, isso tem a ver com o plugin ou não?
