### ISSUE TITLE
Sugestão de melhorias

### ISSUE THREAD

**Issue by stdentoficial** [warleysr/autopix#26]
Caro Warley,

Primeiramente, agradecemos imensamente a disponibilização do plugin **AutoPix**, ele funciona perfeitamente, não tive erros na versão **1.19.4**

Gostaríamos de compartilhar algumas sugestões de melhorias que poderiam ser implementadas em uma próxima atualização:

* Adicionar um método para cancelar o pagamento na API de dentro do server pois os pagamentos vão ficando presos e é necessário realizar o processo manualmente.

* Adicionar uma forma de pagamento via PIX mas pela chave, assim podemos configurar um e-mail padrão no arquivo de configuração e direcionar os pagamentos para lá.

*  A consulta do método automático no arquivo PHP, contém as credencias de banco de dados expostas a internet, uma melhoria seria armazenar essas credenciais localmente no servidor, em um arquivo de configuração por exemplo.

Ficamos a disposição para contribuir nas questões de Segurança e Infraestrutura. 😃

**Comment by warleysr** [comment]
Opa, bacana as sugestões, gostaria de entender melhor sobre elas.

Esse cancelamento de pagamentos seria como e o quê propriamente dito? Os pagamentos ficam pendentes pra sempre você diz? O MP envia o status de cancelado automaticamente quando passa o tempo disponível para pagar, talvez não esteja sendo atualizado com esse status no banco e seja uma questão de ajuste no arquivo PHP.

A questão de pagamento pela chave Pix já existe, é o modo manual. A desvantagem dele é ter que copiar o código do pix e validar com um comando.

Quanto a exposição dos dados não entendi, eles estão hard-coded no código PHP que roda no servidor, então pra acessar eles tem que ter acesso ao mesmo e assim também teria acesso ao arquivo de configuração.

**Comment by stdentoficial** [comment]
Warley, bom dia!

Durante os testes, por algum motivo os pagamentos ficavam pendentes por muito tempo e gerava uma lista enorme, provavelmente o banco não estava recebendo as atualizações dos pagamentos, era necessário acessar o banco de dados e remove-los na mão, porém, se existisse um comando /cancelarpgto para administradores, seria possível enviar um delete do registro para o banco de dados, solicitando a remoção daquele pagamento preso (pelo id do pagamento ou qualquer outra informação chave do pgto), caso não funcionasse ele retornaria erro.

Sobre o arquivo PHP, no nosso caso, o site não fica na mesma região/rede da aplicação, pois existem servidores diferentes para essa finalidade, isso me forçaria a expor o meu banco de dados para a internet, para que eu conseguisse que o PHP comunicasse com ele, já que não estão na mesma rede, uma vez que o arquivo é localmente, não há necessidade de expor o banco para a internet e eu conseguiria consultar o PHP direto da máquina (exemplo).

Caso você tiver outras sugestões sobre o arquivo PHP, podemos mudar a forma que está :D

**Comment by warleysr** [comment]
Opa, no [1131f3e](https://github.com/warleysr/autopix/commit/1131f3e2a957a10cb9a974b05bde9c13c72c864c) alterei pra ler os dados de um arquivo local como sugeriu, se puder testar e me dizer se funciona. 😅 

Quanto a questão do cancelamento ainda tenho algumas dúvidas. Você se refere ao cancelamento da ordem interna no plugin (registro no banco que aparece no /pix lista) ou o pagamento em si no MP ou ambos?

Pensei em colocar um comando `/pix cancelar <Id>` onde o id seria o da ordem, a questão é que não estou associando o id do pagamento do MP na ordem 🙃 , somente o código pix gerado. Colocar para cancelar pelo plugin pagamentos do MP com o código de lá é ruim pois poderá cancelar pagamentos não relacionados ao plugin.

A melhor alternativa é mudar a estrutura da tabela de ordens e salvar o id do pagamento gerado, mas pra isso vou precisar de mais tempo.

**Comment by stdentoficial** [comment]
Caro Warley, bom dia!

Espero que tenha uma excelente semana.

Sobre a questão do cancelamento, acreditamos que o correto seria exatamente o que você passou, coletar as informações do ID dos pagamentos e salvá-los no banco de dados, assim conseguimos cancelar apenas transações que existem dentro do banco, ao invés de possibilitar o cancelamento de qualquer transação na API do MP, o /pix cancelar <ID>, ficou excelente, é exatamente isso!

Vamos aguardar novas atualizações, desde já, agradeço!

Sobre o salvamento local, acho que a nova atualização talvez não atenda a nós, pode ter dado uma confusão durante a explicação.

Mas a ideia era que o arquivo "web\notification.php" fosse salvo localmente no mesmo servidor que está o Minecraft rodando, pois é lá que o banco de dados está rodando e as credenciais irão funcionar localmente, no nosso caso, o servidor de banco de dados do Mine, não fica junto com o site, quando você tentar autenticar com o "localhost" ele não vai encontrar o banco, visto que está em outro servidor, em outro país.

Exemplo: 

No seu arquivo autopix/config.yml, você solicita para especificarmos o site onde o "web\notification.php" está armazenado, correto?

Se o **"notification.php"** estiver rodando em um site localmente **"127.0.0.1"**, neste caso o seu arquivo .php irá funcionar perfeitamente, pois o site se comunica com banco de dados do Minecraft **dentro da mesma rede**.

Se o **"notification.php"** estiver rodando em um site fora da rede local, neste caso o seu arquivo .php não irá funcionar, pois ele tenta se autenticar em um banco de dados, que não está dentro da rede, existe algumas formas de solucionar isso, sendo elas:

1. Permitir que o banco de dados do Mine, aceite conexões externas do site que está em outro país. (Mas não é uma boa prática para o negócio)
2. Migrar o site para a mesma rede do Minecraft, assim tanto o site quando o banco de dados irão se comunicar na rede local e o problema seria resolvido. (Estou avaliando isso no momento, mas inicialmente os gastos seriam muito maiores)

A ideia era fazer o plugin funcionar, sem a necessidade de migração ou expor o banco de dados, por isso eu sugeri, se existia alguma forma de salvar esses arquivos .PHP, dentro do próprio servidor do Mine em algum diretório, exemplo:

Ao invés de especificar o site "https:\\....com.br\web\notification.php" no arquivo **autopix/config.yml**, não conseguimos instalar o PHP na própria máquina local e especificar um diretório dentro do servidor?

Exemplo: "C:\Web\Notification.php" no "autopix/config.yml" Se for possível, isso resolveria todos os problemas!

**Comment by warleysr** [comment]
É possível fazer da forma que você precisa agora, basta hospedar um servidor que rode PHP na mesma máquina do seu servidor de Mine. A questão é que este servidor **precisa** estar exposto a internet, pois o MP faz uma requisição para informar a atualização do status do pagamento. 

Se utiliza uma VPS por exemplo, você poderia instalar o Apache que vai hospedar o **notification.php** mas o banco não precisa permitir conexões remotas, então no **config.json** você manteria o **localhost**. Exemplo:

![image](https://github.com/warleysr/autopix/assets/6331012/772a2887-4c03-4f75-aa7f-a8001490978d)

Veja que tão somente o seu servidor Apache está exposto a internet (e o Spigot também deve estar pra você ter players 😆), mas o MySQL não está, então no **config.yml** do plugin você usará localhost.
