### ISSUE TITLE
| Erro na versão spigot 1.20.4  

### ISSUE THREAD

**Issue by BadBiul** [warleysr/autopix#28]
![image](https://github.com/user-attachments/assets/f82f8a95-2869-4704-9e9f-82593be71ba1)
![image](https://github.com/user-attachments/assets/d107513f-cb8e-4c7e-a3c8-41b30161a472)

nome do erro: an internal error occurred while attempting to perform this command

[message.txt](https://github.com/user-attachments/files/16743503/message.txt)

**Comment by warleysr** [comment]
A mensagem no início diz "plugin is disabled". O plugin não foi ativado corretamente, veja na inicialização qual mensagem está aparecendo. Provavelmente não conseguiu conectar ao banco de dados.

**Comment by warleysr** [comment]
@BadBiul Cara deletei seu comentário porque tinha informações sensíveis nele. Tanto do banco de dados quanto do MercadoPago. Do jeito que você ocultou ainda dava para ver tudo 😅.

A questão do banco de dados você tem que ver se o banco aceita conexão remota. Para testar isso sugiro baixar o MySQL Workbench e tentar conectar através dele com as mesmas informações da config. Você usa esse banco em algum outro plugin?

Veja a inicialização do servidor, quando o plugin é desativado ele deve mostrar alguma mensagem explicando o motivo. A versão do Spigot não deve ser o problema aqui.

**Comment by BadBiul** [comment]
obg por ter apagado, nem prestei muita atenção enquanto a isso, a host que uso já tem um MySQL e sim usei esses bancos de dados em um outro plugin mais ai eu apaguei o outro e deixei só o autopix mais mesmo assim fica aparecendo esse erro e eu realmente queria esse plugin, ele precisa de algum outro plugin para funcionar?

**Comment by warleysr** [comment]
Não precisa, só precisa de conseguir conectar no banco.

Você conseguiu fazer o teste que sugeri? Reinicia o server e acompanha o log durante a inicialização, deve aparecer alguma mensagem do tipo: ‘[AutoPix] Erro ...‘

Coloca ela aqui

**Comment by BadBiul** [comment]
mais eu já mandei 2 prints com o erro que dá quando eu ligo/reinicio, eu acho que é porque eu não sei se coloquei os dados corretos pois não tem um tutorial mostrando sobre esse plugin passo a passo e como eu não entendo sobre quais dados colocar daí complica :(

![image](https://github.com/user-attachments/assets/e6f88efc-b6fd-4b08-9eb6-b45d078d9d40)

**Comment by warleysr** [comment]
Pronto, tá aí o problema, não foi possível conectar ao banco. Provavelmente sua host não aceita conexão remota, ou você colocou alguma informação errada mesmo.

Não estou disposto a gravar tutorial sobre como configurar porque não difere de outro plugin qualquer.

Faça o teste que sugeri usando o MySQL Workbench para testar a sua conexão. Também é possível mudar o tipo do banco para sqlite na config e com isso você consegue testar o plugin. Esse tipo de banco cria um arquivo .db na pasta do plugin, só fique atento pois se deletar a pasta ou esse arquivo perderá seus dados.

**Comment by BadBiul** [comment]
![image](https://github.com/user-attachments/assets/23a1def3-3862-4c23-b251-e606afe9f343)

a host já vem com o MySQL eu só crieio e coloquei os dados, só não sei se coloquei certo

vc não precisa gravar um turorial mais se vc tiver discord e for possivel me ajudar remotamente por lá já que aqui não posso msotrar os dados eu ficarei grato :(

**Comment by warleysr** [comment]
Não tenho disponibilidade. Faça os testes que estou sugerindo:

 1. Usar o MySQL Workbench pra testar a conexão remota (https://www.youtube.com/watch?v=s0YoPLbox40). Você vai adicionar uma outra conexão com os dados do seu painel.
 2. Mudar para `sqlite` e usar como arquivo.

**Comment by BadBiul** [comment]
Ok, obrigado! 
:(
