### ISSUE TITLE
Agradecimento 

### ISSUE THREAD

**Issue by BattleMN** [warleysr/autopix#29]
Boa noite, estou usando o plugin desde que me ajudou ajeitar ele, é um plugin incrível e o melhor é que não precisa criar ter um site para conseguir utilizar. Eu gostaria de saber se você pretender lançar atualização dele futura, com um /autopix reload - para não precisar reiniciar toda vez que for adicionar ou mudar algo, Se sim também gostaria de saber c tem como colocar um top donator para saber o player que mais adquiriu com o plugin. Seu plugin é simples e perfeito de usar, queria agradecer.

**Comment by BattleMN** [comment]
Pode me chamar no dc? tenho uma proposta pra ti, meu discord é angel.without.light

**Comment by warleysr** [comment]
Opa, não tenho disponibilidade de fazer projetos privados. Quanto aos pedidos de melhoria achei interessantes e não são simples de implementar. Vou adicionar na próxima versão, quando tiver tempo.

**Comment by warleysr** [comment]
Adicionei os comandos na versão [v1.0.19](https://github.com/warleysr/autopix/releases/tag/v1.0.19).

**Comment by BattleMN** [comment]
Muito obrigado!!
