### ISSUE TITLE
QRCode invalido ao escanear

### ISSUE THREAD

**Issue by SrSendus** [warleysr/autopix#3]
Estou tendo problemas ao utilizar o plugin com a opçao de ativaçao automatica desativada... ele gera o QRCode que na hora de escanear no app do bando o QRCode é invalido, testado em 3 apps de banco e nao apresenta erros no console..

**Comment by warleysr** [comment]
Qual tipo de chave você tá utilizando? E como ela está configurada?

Omite parte dela para não expor os seus dados e me manda aqui.

**Comment by SrSendus** [comment]
Estou usando uma chave pix de um email @gmail.com
![Sem título](https://user-images.githubusercontent.com/38896277/235132401-4f6a8241-1879-4148-b8d5-1b7bcbbce4e1.png)

**Comment by warleysr** [comment]
Certo. Vou tentar reproduzir aqui.

**Comment by SrSendus** [comment]
Ok amigo, estou no aguardo, se serve de ajuda, tentei trocar a chave pix por uma aleatoria e o problema persiste.
Os digitos do nome do beneficiario junto dos espaços somam 24 caracteres.

**Comment by warleysr** [comment]
Qual erro aparece quando você tenta ler o QR code? Testei aqui com uma chave gmail e está funcionando. O nome não importa muito, pode deixar 'Fulano de Tal' mesmo que vai aparecer o nome que está associado na chave PIX.

Você está usando a última versão do plugin? É a v1.0.4

**Comment by SrSendus** [comment]
Estou utilizando a mais recente. v1.0.4 
![2225230d-e52a-40e8-a637-c63dfdea1b56](https://user-images.githubusercontent.com/38896277/235324698-1fac0ce9-5cf0-4748-a54f-405dd2423c07.jpg)

Será que pode ser pq o MySQL está em localhost?

**Comment by warleysr** [comment]
Não, o QR code nem seria gerado se houvesse erro no MySQL. Essa chave está cadastrada em algum banco? 

Se sim, tenta em outro aplicativo que escaneie. 

Tenta também gerar o código através deste site: https://www.gerarpix.com.br/

Coloca as mesmas informações da config lá e tenta gerar. Se der certo pelo site, vou colocar uma opção de debug para comparar o texto gerado lá com o texto gerado pelo plugin.

**Comment by SrSendus** [comment]
Utilizo somente no mp. criei o email justamente para isso. testei o site com as mesmas informaçoes, e o app do banco escaneou certinho

**Comment by warleysr** [comment]
Certo, baixa esse jar e substitui na pasta. Quando você gerar um QR code ele vai mostrar no console uma mensagem assim:
![image](https://user-images.githubusercontent.com/6331012/235326644-352ec483-84c1-461a-b07b-9c5f35576d02.png)

Esse texto é a informação que o QR code armazena, que seria o "pix copia e cola".

Com esse texto você usa um checador de diferenças como o https://www.diffchecker.com/ para verificar a diferença entre o gerado pelo site e o gerado pelo plugin.

Pode ser também o nome do produto. Faz essa análise e me mostra os resultados.

**Comment by SrSendus** [comment]
Fiz os testes, 
![Screenshot_2](https://user-images.githubusercontent.com/38896277/235340359-2ed25cab-8fe5-4f27-bcdb-14fbb3c6a1be.png)

Sobre o nome do produto, eu nao adicionei nenhum ainda só renomeei o da config padrao de VIP1 par VIP para fazer os testes se funcionava 100% e ja deparei com o problema

**Comment by SrSendus** [comment]
Fiz os testes.

O primeiro em vermelho foi o gerado pelo Plugin e o segundo em verde pelo site https://www.gerarpix.com.br/
![Screenshot_2](https://user-images.githubusercontent.com/38896277/235340576-28cae798-e1ff-4677-9d35-9c4a3aef1514.png)

Sobre o nome do produto, eu nao adicionei nenhum ainda só renomeei o da config padrao de VIP1 par VIP para fazer os testes se funcionava 100% e ja deparei com o problema

**Comment by warleysr** [comment]
Acredito que você quis dizer que o vermelho é pelo site e em verde pelo plugin.

Há apenas uma diferença que é o "6208" ao invés de "6207" depois de "BRASILIA". Pode ter ocorrido alguma atualização que mudou esse código. Testei aqui pelo banco Inter e tanto o com 6208 quanto com 6207 estão funcionando. Talvez alguns bancos só aceitem com 6207.

Baixa esse jar que agora está usando 6207 e substitui na sua pasta e faz o teste para ver se a Caixa reconhece o código. Se preenchido os valores iguais da config o diff checker não deve apresentar nenhuma diferença com a gerada pelo site.
[AutoPix-DEBUG_v2.zip](https://github.com/warleysr/autopix/files/11362085/AutoPix-DEBUG_v2.zip)

**Comment by SrSendus** [comment]
Refiz os testes, ainda persiste o erro, testei tambem nos banco PicPay e Nubank tambem deu invalido.
![Screenshot_6](https://user-images.githubusercontent.com/38896277/235408978-b14b1392-cae7-4365-8165-19398f31ae45.png)

E sim, inverti a informaçao no comentario anterior.

Ah uma diferença apos o item VIP mas acredito que isso seja só referente ao item

**Comment by SrSendus** [comment]
Refiz os testes, ainda persiste o erro, testei tambem nos banco PicPay e Nubank tambem deu invalido.

![Screenshot_6](https://user-images.githubusercontent.com/38896277/235409404-5470f6e3-956e-48ac-b0c6-81b0d76c478a.png)

Ah uma diferença apos o item VIP mas acredito que isso seja só referente ao item

**Comment by warleysr** [comment]
Lancei a [v1.0.5](https://github.com/warleysr/autopix/releases/tag/v1.0.5) que conserta esse bug. Baixe ela em releases e faça os testes nessa versão. O problema era que estava fixo para um tipo de chave, fiz o teste com todos tipos de chaves e aparentemente está correto agora.

**Comment by SrSendus** [comment]
Testei e funcionou. o QRCode funcionou perfeitamente. porem, a transaçao fica como pendente e nao aprova. fiz dois testes de transações com bancos diferentes e ambos ficaram como pendente, esperei 30 minutos para ver se mudava o status e continua como pendente. sendo impossivel utilizar o comando /pix ativar pois no /pix lista fica como pendente
![Screenshot_7](https://user-images.githubusercontent.com/38896277/235470686-7880a4bc-5746-4625-9dee-80b7132184c2.png)

**Comment by warleysr** [comment]
Não entendi, você tá usando o modo automático ou manual? O modo manual (que é o que você estava usando) o jogador tem que validar a transação com /pix validar. Use /pix info para saber mais.

O modo automático necessita de configurar o PHP em um servidor acessível a internet.

**Comment by SrSendus** [comment]
Estou usando o modo MANUAL pois nao tenho hospedagem no momento.. quando dou /pix lista para ver as transações ela fica sempre como PENDENTE. quando dou /pix validar com o codigo ele da erro ao validar
![Screenshot_8](https://user-images.githubusercontent.com/38896277/235472374-9cbd3bd9-cf0c-4a9b-929b-c71519f02eb3.png)

**Comment by warleysr** [comment]
Pega o erro que aparece no console ao executar o comando e posta aqui.

**Comment by SrSendus** [comment]
Ele nao apresenta erros no console..
![Sem título](https://user-images.githubusercontent.com/38896277/235473020-28df80a7-1921-4933-8f7e-2e7928625fc6.png)

**Comment by warleysr** [comment]
Certo, então não aconteceram erros na validação, ele não foi capaz de encontrar essa transação no MP.

1. Entre no MP que você usou para gerar o QR code e procura a transação que realizou o pagamento
2. Clique para ver os detalhes e verifique se o código mostrado lá é igual ao código que você tentou usar 
![image](https://user-images.githubusercontent.com/6331012/235474869-f40e0abc-b723-46f0-8e31-2814dbf0eaa1.png)

**Comment by SrSendus** [comment]
Sim, eu verifiquei antes mesmo de fazer o comando se o codigo estava correto.
![fbfa34e5-f7fd-412e-8398-aee40304e7cf](https://user-images.githubusercontent.com/38896277/235477225-3fc2a82a-1dd8-4efa-9791-b303e7e9fe8b.jpg)

**Comment by warleysr** [comment]
A comparação do valor pago com o valor da ordem salva no banco de dados estava incorreta. As lógicas estavam diferentes para o modo manual e o automático (que funciona). Consertei isso na [v1.0.6](https://github.com/warleysr/autopix/releases/tag/v1.0.6), substitui o jar e faça os testes.

**Comment by SrSendus** [comment]
![Screenshot_9](https://user-images.githubusercontent.com/38896277/235490417-25214220-38ef-426c-80fe-d7d3b91544d7.png)
Funcionando perfeitamente! plugin otimo, deveria ser pago de tao bom.. Muito obrigado pelo suporte!
