### ISSUE TITLE
Problemas no QRCode

### ISSUE THREAD

**Issue by SrSendus** [warleysr/autopix#4]
Bom dia, sou eu novamente, estou utilizando em meu servidor seu plugin porem desde ontem ele começou a gerar QRCodes sem valor quando escaneados, alguns com valores absurdamente alto e incorreto
QRCode Gerado:
![Screenshot_20](https://github.com/warleysr/autopix/assets/38896277/ca4cab64-c9e1-49ea-b971-4994c913e557)

Print banco Caixa:
![Caixa](https://github.com/warleysr/autopix/assets/38896277/c6df7c35-a5d2-46af-986a-cda6ef28197e)

Print do banco PicPay
![PicPay](https://github.com/warleysr/autopix/assets/38896277/9474396d-3d5c-4ede-8853-2aa48b89638c)

**Comment by warleysr** [comment]
Remove os dados confidenciais e posta sua config aqui para eu ver o que pode estar acontecendo.

**Comment by SrSendus** [comment]
[config.txt](https://github.com/warleysr/autopix/files/11469713/config.txt)

**Comment by warleysr** [comment]
Isso acontece em algum item específico? Não consegui reproduzir o problema.

**Comment by SrSendus** [comment]
Acontece com qualquer item

**Comment by warleysr** [comment]
Sim, todos os QR codes gerados estão funcionando. Testei quase todos os itens. Tentei escanear com o Banco Inter e com o 99Pay.
![image](https://github.com/warleysr/autopix/assets/6331012/c5e77dc1-76e8-46d6-b465-267b5b4da12f)

**Comment by SrSendus** [comment]
Estranho, pois aqui qualquer item acontece o problema, tentei tambem resetar a config do plugin e tambem persistiu. estou usando a ultima vesão

**Comment by warleysr** [comment]
Qual versão do Spigot você está usando?

**Comment by SrSendus** [comment]
1.8.8

**Comment by warleysr** [comment]
Testei aqui e está funcionando no Paper 1.8 também. Realmente muito estranho começar a acontecer isso do nada, tente se lembrar de algo que você tenha mudado na config. As informações que são utilizadas para gerar o QR code são:

- A chave PIX
- O nome do recebedor (que geralmente não aparece na hora do pagamento, então pode ser 'Fulano de Tal' mesmo)
- A descrição do item (chave que identifica o produto na config)
- Preço do produto

Se não conseguir contornar o problema recomendo usar o modo automático, nele o QR code é retornado pelo MercadoPago.

**Comment by SrSendus** [comment]
Sim, a unica coisa que fiz foi passar o servidor para uma VPS, apos isso o problema aconteceu. testei aqui e na maquina antiga funciona.. vou ver oque pode ser obrigado.

**Comment by SrSendus** [comment]
Após alguns testes identifiquei este erro no console

[20:32:38 INFO]: SrSendus issued server command: /pix validar E00360305202305140032e7fdb886eb8
[20:32:40 WARN]: java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.Double (java.lang.Long and java.lang.Double are in module java.base of loader 'bootstrap')

[20:32:40 WARN]:        at io.github.warleysr.autopix.qrcode.MPValidator.validateTransaction(MPValidator.java:60)

[20:32:40 WARN]:        at io.github.warleysr.autopix.commands.AutoPixCommand.lambda$0(AutoPixCommand.java:80)

[20:32:40 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
